version: '3.7'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_EDAD=32
    environment:
      - VITE_APELLIDO=Skorpio
    ports:
      - '80:80'

    